### ISSUE TITLE
AttributeError: 'Predictor' object has no attribute 'get_dimensions'

### ISSUE THREAD

**Issue by immex-tech** [fofr/cog-lcm#2]
When I choose Input_image as sizing strategy => 

Using seed: 10379
Found 1 prompt:
- minimalist family room
Making 1 image
Resizing based on input image
Traceback (most recent call last):
File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
^^^^^^^^^^^^^^^^^^
File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/src/predict.py", line 285, in predict
) = self.apply_sizing_strategy(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/src/predict.py", line 153, in apply_sizing_strategy
width, height = self.get_dimensions(image)
^^^^^^^^^^^^^^^^^^^
AttributeError: 'Predictor' object has no attribute 'get_dimensions'

**Comment by fofr** [comment]
@immex-tech Do you have a link to your prediction to help me debug?

**Comment by immex-tech** [comment]
here: https://replicate.com/p/ji2vvhbbaqxsbgvxy7wn3pzeb4?input=form

**Comment by fofr** [comment]
Thank you for reporting this, it's fixed in:
https://replicate.com/fofr/latent-consistency-model/versions/a83d4056c205f4f62ae2d19f73b04881db59ce8b81154d314dd34ab7babaa0f1

https://github.com/fofr/cog-lcm/commit/681edebfea16f1ed31cf25987f79bc55a9f05f89
